### ISSUE TITLE
Doc: Enhance Oqtane Framework Documentation for Installation

### ISSUE THREAD

**Issue by thabaum** [oqtane/oqtane.docs#41]
# Enhance Oqtane Framework Documentation for Installation

## Description
This issue is to discuss and track the necessary enhancements to the Oqtane Framework documentation. The goal is to ensure that the documentation is up-to-date with the latest version of Oqtane and provides comprehensive guidance on installation, configuration, and support for different hosting environments.

## Tasks
- [x] Update the installation and configuration instructions for Windows and Linux.
- [x] Enhance the documentation for supported SQL databases (PostgreSQL, MySQL, LocalDB, SQL Server).
- [x] Provide detailed steps for hosting Oqtane Framework locally and on cloud platforms.
- [ ] Document advanced configuration options, including multi-database support and cross-platform support.
- [ ] Update the troubleshooting section with common issues and solutions.
- [ ] Expand the FAQ section to cover more questions about Oqtane Framework's installation, configuration, and supported environments (Windows, Linux, IIS, IIS Express, Visual Studio, VS Code??, etc...)

## Additional Context
I will assist with this when visiting each relating area described.  This issue is for anyone that wishes to point out how we can improve this process.  Please let us know by creating an issue or posting here of any missed steps, suggestions or issues you have so we can provide fully enhanced documentation support.

One last note is any issue I post, everyone, anyone is welcome to contribute to as well.  I know many of you can do this better than I can, and there already are a lot of support docs included here which can be used to merge any enhancement ideas, such as a missing step worth noting.  

Every little bit can anyone can contribute will help limit future support issues in the framework repository leaving more time for project maintainers to focus on enhancements and bug fixes.  Do what you can, when you can, as you feel like it.  Thank you.

**Comment by thabaum** [comment]
https://github.com/oqtane/oqtane.framework/discussions/3695#discussioncomment-8331427

This issue shows most steps needed for how to install on Linux, Ubuntu with Apache and some info for Nginx.

**Comment by iJungleboy** [comment]
Wow that's some intensive 💩!!

so you'll reduce it to readable portions into the docs?

**Comment by thabaum** [comment]
That's the plan.  I am just taking notes as I go in different areas.  I will consolidate them into a very legible instruction set.  I will do this for all installation types supported for Oqtane with images.  Then I will submit a PR for you to review and enhance as needed so things are clear anyone can easily fire it up with the flavor they want.

**Comment by thabaum** [comment]
Or how would you think is best?  I can produce it here in GitHub issues as well.  It is a task to setup Linux, took me a day to work through it for a first time.

**Comment by iJungleboy** [comment]
Sounds awesome. 
Just go ahead and write and push.

Note that I'll be on ski vacation next week, so you won't hear from me during that time. 
Will try to attend the Oqtane meeting though. 

Looking forward to SSR :)

**Comment by thabaum** [comment]
@iJungleboy It looks like I laid out quite a spell for myself, I am going to approach this in chunks and enhance further as we go so maybe I will start these off initially as "draft" when ready for first reviews of a pull request relating to each section of these guides.

Here is the current master plan please let me know your thoughts:

- I am going to focus on Windows and Apache installations, use what is available for Azure I can find since I do not have an account to test this.
- I will work on providing resources and basic instruction to setup and test the various supported database and web servers.  This will include links and images along with step-by-step examples.
- These will be located in the current `Guides` section of documentation under a new section called `Getting Started` which will have additional sections something similar to as shown below:

# Getting Started

## Installation
### Windows
- Instructions for Windows installation
### Linux
- Instructions for Linux installation
- Special instructions for Ubuntu Desktop

## Web Servers
### Windows
- Internet Information Services (IIS)
- Apache
- Nginx
### Linux
- Apache
- Nginx

## Database Servers
### Windows
- MS SQL Server
- LocalDB
- MySQL
- PostgreSQL
### Linux
- MySQL
- PostgreSQL

## Azure Deployment
- Instructions for deploying to Azure using the "Deploy to Azure" button
  
![image](https://github.com/oqtane/oqtane.docs/assets/13577556/56d04973-7794-46b8-92ea-3466770534ef)

Let me know if this makes sense?

**Comment by iJungleboy** [comment]
I think this sounds good. I have a few thoughts on this

1. I would invest the resources on likely scenarios. Eg. Windows will be 99% IIS, so I would not prioritize exotic setups like Apache on windows 
1. Under DB servers - did you want to provide instructions to install the DB server, or how to prepare-configure it, or what to do during installation? If it's really just the oqtane-installation part, I would also put it directly under the "windows installation" topic, not much further down. 

thx!

**Comment by thabaum** [comment]
> I would invest the resources on likely scenarios. Eg. Windows will be 99% IIS, so I would not prioritize exotic setups like Apache on windows

I will keep these as basic getting started guides prioritizing Windows IIS and Azure first and then a few linux guides to help someone get started along with links to resources.

> Under DB servers - did you want to provide instructions to install the DB server, or how to prepare-configure it, or what to do during installation? If it's really just the oqtane-installation part, I would also put it directly under the "windows installation" topic, not much further down.

We can break things up by Windows Installation and Linux Installation and then group sub categories of the technologies that are available and supported by Oqtane for each.

I think what I will do is create each of these as a draft and then we can merge one or two at a time.  I will leave it open for maintainer edits so you can enhance it further as we go as well making sure we dont miss any crucial steps and instructions are very clear and easy to follow.

I am not 100% on exactly how we layout all of this.  We may combine all under windows and the rest under Linux and branch off from there into the docs for relating resources.  I am flexible here, and as we start putting this together things may need to pivot away from the original layout.

I will work on Windows only today/tomorrow as permitted and see how it goes.

**Comment by thabaum** [comment]
@iJungleboy thank you for directing me to and updating the installation manuals section page examples for me to start providing.  The path to updating the User Manual section transformation mission phase 1 is now in progress.  After our discussion I believe I will personally focus mainly on the User Manual area until after 5.1 updates are complete.  I should have the Windows and Linux #1 setups complete as discussed by the end of the weekend.

**Comment by thabaum** [comment]
Hello Fellow Oqtane Doc Supporters!

Today I am going to work on a page for instructions for installing Oqtane Framework on Windows with IIS and MS LocalDb.  It will be similar for all other supported databases with a bit different setup I will work into the mix later.

I am currenly using https://www.oqtane.org/blog/!/24/installing-oqtane-on-iis for a reference.  I will add pictures to this as I create the manual.  Any ideas are more than welcome at this point to be sure this is going to be the best.  Please take time to review things below to be sure I am making things clear and not missing anything:

# Installing Oqtane Locally on Windows 10 with IIS

## Step 1: Install IIS

- Search for "Turn Windows features on or off" next to the Windows Start button.
- Enable Internet Information Services (IIS) ensuring WebSocket Protocol is enabled and WebDAV Publishing is disabled.
- Click OK to complete the installation.

*Note: Ensure that the WebSocket Protocol is enabled and WebDAV Publishing is disabled to avoid conflicts with Blazor.*

## Step 2: Install Url Rewrite Module

- Navigate to [Url Rewrite Module](https://www.iis.net/downloads/microsoft/url-rewrite).
- Download and install.

*Note: The URL Rewrite Module is necessary for configuring URL rewriting rules in IIS, which are often used in web applications like Oqtane.*

## Step 3: Install .NET Core Hosting Bundle

- Navigate to [.NET Core Hosting Bundle](https://dotnet.microsoft.com/permalink/dotnetcore-current-windows-runtime-bundle-installer).
- Download and install the bundle.
- Restart your machine.

*Note: The .NET Core Hosting Bundle is required for hosting .NET Core applications on Windows servers.*

## Step 4: Install LocalDB

- If doing a local install and wanting to use LocalDB for development, navigate to [LocalDB installation](https://docs.microsoft.com/en-us/sql/database-engine/configure-windows/sql-server-express-localdb?view=sql-server-ver15) and choose Express Advanced or the LocalDB package to install.

*Note: LocalDB is recommended for development environments but can be substituted with other database options supported by Oqtane such as SQLite, MySQL, PostgreSQL, or SQL Server.*

## Step 5: Install Oqtane

- Download the latest Install package from [Oqtane Releases](https://github.com/oqtane/oqtane.framework/releases).
- Extract the files to your desired directory.

*Note: Extract the files to a directory where you plan to host your application.*

## Step 6: Configure IIS App Pool

- Open "Internet Information Services (IIS) Manager".
- Add a new Application Pool with the name "oqtane" and set ".NET CLR version" to "No Managed Code".
- Set the Identity to "LocalSystem" in Advanced Settings.

*Note: Setting the App Pool's Identity to "LocalSystem" is necessary for IIS to interact with the file system and LocalDB.*

## Step 7: Configure IIS Website

- In IIS, right-click on Sites and select "Add Website".
- Provide a name and choose the Application Pool created earlier.
- Specify the path to the Oqtane files.
- Specify a Host name, e.g., "oqtane.dev".

*Note: Ensure that the host name specified here is correctly mapped to the machine in the host file.*

## Step 8: Add a Host Entry

- Open Notepad as Administrator.
- Open the "hosts" file located in `C:\Windows\System32\drivers\etc`.
- Add an entry mapping the host name to 127.0.0.1, e.g., "127.0.0.1 oqtane.dev".
- Save the file.

*Note: This step is only required for a local development environment. In shared or public environments, standard DNS configurations are used.*

## Step 9: Navigate to Site

- Open your favorite browser and navigate to the specified host name, e.g., `http://oqtane.dev`.
- Follow the Oqtane install wizard, providing necessary database connection details and site administrator credentials.
- Click Install.

*Note: If encountering errors during the Install Wizard due to database creation permissions, consider creating the database manually before initiating the Install Wizard.*

**Comment by thabaum** [comment]
@sbwalker I have a concern with the current installation instructions.  Generally when I set up a site, I add the IIS AppPool\Identity to the folder and give it "modify" writes and everything works great, not an issue yet that I can find.  I dont give "full" because why if "modify" will do it?  For security always use the least permissions you can allow, correct?

Using a more restricted identity for the App Pool improves security by limiting the privileges of the application to only what is necessary, reducing the potential impact of security vulnerabilities. Therefore, it's generally recommended to follow the principle of least privilege and assign permissions granularly rather than relying on a high-privileged account like "LocalSystem".

**Comment by thabaum** [comment]
FYI anyone interested I am working on the enhanced installation docs to submit for review here:  https://github.com/thabaum/oqtane.docs/tree/installation-demo

This is more or less a general outline of the process, some steps still need full updated, enhanced and corrected.  In fact I may have 2 steps on one to review which version I will keep.

This is so I can review how things look and store my progress in one place.

My current goals is to setup a way to review your sites in more of a production environment but can be used to test development as well.  I wont be focusing on the "SSL' side of things for now, this can be added later however there will be guidance to resources to help in these areas.

I include pages as follows:

Installation
- Index
- Windows, IIS, SQL
- Windows, IIS Express, SQL Express
- Windows, IIS (Express), LocalDb
- Linux, Ubuntu, Apache, MySQL
- Linux, Ubuntu, Apache, PostgreSQL
- Databases
- Resources
- Upgrades

A few more install pages now or down the road not mentioned since I do not have these environments to test which would be:

- Deploy to Azure
- Docker
- Web Farm

Databases holds ALL the supported database information and resources for both Windows and Linux for each flavor.

Resources holds ALL the links in the installation section plus more organized to help anyone get heading in the right direction quickly.

Upgrades I migrated the blog article to it's own page in docs.  I hope @sbwalker has no problem with us doing this as it was my plan to take work already done and merge it over to docs as much as I can.  I was hoping we all can start doing this.

I may add a Redhat/Fedora setup upon request but I am sticking with Ubuntu for now.  I may do this with NGinx, or do one Linux Ubuntu with Nginx and one with Apache.

This should cover most all the basics to get started with any build you wish to stack Oqtane on top of.  However I may simplify areas that I could point to a guide that best explains such as installing Ubuntu.

You have to forgive me for being a bit of a perfectionist as I do and still come up with stuff not accepted.  No worries this was a ton of work already, but I need to actually walk through each manual next add images were applicable and ensure no steps are missing or redundant.

I copied what I could and modified things as I seen fit for documentation.  Again I will add some images to color everything up last touch no problem.

@iJungleboy I wanted to change "index.md" to "overview" so need to do a few things maybe to make this happen with URL redirections?

I believe we should maybe make an issues or troubleshooting and tips sections.  Put a few for placeholders to grow as contributions come to help out the next.

Anyhow this is an update as I had stuff done for about a week, and just applied things to the branch link provided.  It is hard for me to just put my toes in and work on one doc for this situation... sorry @iJungleboy ... when I get into something I go all in so I am heading more for the entire installation section being done in my opinion enough to help anyone get started with Oqtane Framework with most any environment supported.  

This approach is giving me any final ideas to pivot on as I see all the versions and differences in installation processes.  Some of them are the same and I would not mind having a page for "Install, Setup IIS" and one for "Install, Setup Apache" for example and then add it to the pages that use them.  Then there would be links to just this specific information if you're stuck on that step you can get a focused instruction set.  This would also make it easier to maintain one page for that set of instructions long term.

For now I will just make the instructions, we can break things up if desired more later unless I get some instructions to do so.

I would love some feedback but generally have to wait until next doc meeting for any real context.

Maybe we can get some community help here once the pages and sections are built.  If not I will eventually get around to them when I myself work/test in these areas for my own interests.

One last note is I also remade the index.md file to show links with descriptions to areas.  I did a few more things than just what I am talking here and will change things as I go so nothing is in stone yet.

**Comment by iJungleboy** [comment]
@thabaum the `index.md` is the default file so if you link a folder, it's the primary file. There is no configuration that would change this, and it would also confuse future editors.

But you can of course always change the label in the TOC to say "Overview".

Note that 99.9% of users can't really give feedback unless they see it generated, since the effort to rebuild-just-to-give-feedback is too high for most users. So feel free to push and then collect feedback.

**Comment by thabaum** [comment]
@iJungleboy thanks for the feedback.  I will have this done this week for sure (80% +) a full work over as described.  I want to go through things bit more and clean it up for the initial presentation.  This helps clear the path forward.  I already added the deploy to azure page, although I have no azure account we can all improve this as we review as well.  I may create one just to create the manual.

Thank you.
